function AboutPage() {
  return (
    <div className="text-center p-10">
      <h1 className="text-2xl font-bold my-4">About</h1>

      <p className="text-gray-300">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod itaque, dicta optio nam qui modi. Saepe quisquam nihil autem? Labore quia, eius consectetur sit fugiat ex fuga nobis quod pariatur aperiam voluptatum incidunt veniam mollitia laudantium voluptate minus iste harum? Quisquam cupiditate doloribus omnis voluptatem! Explicabo sit corporis totam vero assumenda, necessitatibus distinctio, itaque laudantium voluptatibus odio, tempore ea ut aut voluptatem alias nobis ducimus. Commodi culpa, laborum, repellat fugiat consectetur voluptatum optio sequi dolorem quia eum totam voluptatem sint, quidem aut maxime doloremque minus debitis cupiditate ducimus corporis nihil! Quisquam nisi hic enim temporibus. Officia iusto numquam, deleniti totam cupiditate, rem, illo sequi enim consectetur consequuntur harum nam. Sequi consequuntur illum autem, sapiente eveniet ipsum facilis. Commodi aliquid aliquam ducimus fuga labore fugit natus repellat tempore voluptatum esse, in sunt praesentium deserunt alias, molestias recusandae amet ipsa eius, minima excepturi! Numquam dicta eveniet itaque est voluptas expedita laborum ipsa cumque repellat, quod quisquam officiis voluptatem, minima ducimus! Magni quod est earum eaque quidem itaque eum vitae eos deserunt, quibusdam quia, provident sit necessitatibus molestias inventore. Consectetur eos rem optio ratione! Vero neque commodi ex aut eaque earum minus amet nesciunt eum similique, facilis iste mollitia tempore sequi. Cum ad beatae pariatur veritatis. Iure sint, aspernatur quaerat enim consectetur ipsam inventore qui, at voluptatibus fuga ab id. Commodi vel inventore alias, id aliquam assumenda aperiam sit animi provident quam, quo impedit fugiat. Dicta veniam placeat assumenda quas sapiente, vitae nobis ullam eaque veritatis ex quibusdam voluptates exercitationem officia saepe, ea id consectetur dolorem provident minima, architecto quidem. Vitae quaerat impedit nostrum mollitia facilis aspernatur reiciendis, repellendus ea ullam quos in illum optio dolor harum consectetur quae adipisci, tenetur alias quia! Et sit possimus aliquam cumque quasi eveniet, sapiente sequi! Voluptatum nemo velit nihil id non aliquid placeat ipsum quod eius?</p>
    </div>
  );
}

export default AboutPage;
